api_version = "2026-07"

name = "Reach Order Enrichment"
handle = "reach-order-enrichment"
type = "ui_extension"
uid = "09f0d9c5-709d-41f0-bf6d-5644d874689e"

[[targeting]]
module = "./src/index.js"
target = "purchase.thank-you.block.render"

[capabilities]
network_access = true
block_progress = false
