# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The API version your extension will receive.
api_version = "2026-07"

[[extensions]]
name = "reach-order-enrichment"
handle = "reach-order-enrichment"
type = "ui_extension"
uid = "56b6a3da-5cdb-7aa1-c29d-3d817fe05a0c796777f9"

[[extensions.targeting]]
# Entry module for this extension
module = "./src/index.js"
# The specific checkout target this extension runs on
target = "purchase.thank-you"

[extensions.capabilities]
api_access = true
network_access = true
block_progress = false
